[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "creator-video"
version = "0.1.0"
description = "App modular para fabricar vídeos com IA + ffmpeg"
readme = "README.md"
requires-python = ">=3.10"
[
  "aiohappyeyeballs==2.6.1",
  "aiohttp==3.13.1",
  "aiosignal==1.4.0",
  "annotated-types==0.7.0",
  "anyio==4.11.0",
  "attrs==25.4.0",
  "cachetools==6.2.1",
  "certifi==2025.10.5",
  "charset-normalizer==3.4.4",
  "colorama==0.4.6",
  "edge-tts==7.2.3",
  "frozenlist==1.8.0",
  "google-ai-generativelanguage==0.6.15",
  "google-api-core==2.26.0",
  "google-api-python-client==2.185.0",
  "google-auth==2.41.1",
  "google-auth-httplib2==0.2.0",
  "google-genai==1.46.0",
  "google-generativeai==0.8.5",
  "googleapis-common-protos==1.70.0",
  "grpcio==1.75.1",
  "grpcio-status==1.71.2",
  "h11==0.16.0",
  "httpcore==1.0.9",
  "httplib2==0.31.0",
  "httpx==0.28.1",
  "idna==3.11",
  "multidict==6.7.0",
  "propcache==0.4.1",
  "proto-plus==1.26.1",
  "protobuf==5.29.5",
  "psycopg2==2.9.11",
  "pyasn1==0.6.1",
  "pyasn1_modules==0.4.2",
  "pydantic==2.12.3",
  "pydantic_core==2.41.4",
  "pyparsing==3.2.5",
  "python-dotenv==1.1.1",
  "requests==2.32.5",
  "rsa==4.9.1",
  "sniffio==1.3.1",
  "tabulate==0.9.0",
  "tenacity==9.1.2",
  "tqdm==4.67.1",
  "typing-inspection==0.4.2",
  "typing_extensions==4.15.0",
  "uritemplate==4.2.0",
  "urllib3==2.5.0",
  "websockets==15.0.1",
  "yarl==1.22.0"
]

[project.scripts]
creator-video = "creator_video.cli:main"
